-- TOTP secrets, one per Keycloak subject.
--
-- The secret is stored AES-256-GCM encrypted; `nonce` is the 96-bit nonce used
-- for that particular ciphertext and is unique per row and per rewrite.
create table totp_secrets (
    subject          text        primary key,
    encrypted_secret bytea       not null,
    nonce            bytea       not null,
    created_at       timestamptz not null default now(),
    last_used_at     timestamptz
);

-- Audit trail for PIN requests. Deliberately holds no PIN and no secret.
--
-- `subject` is nullable on purpose: a token rejected by introspection carries no
-- usable `sub`, and those denials are exactly the ones worth recording.
-- `id` is generated by the application rather than by `gen_random_uuid()`, which
-- is only built in from PostgreSQL 13 and otherwise needs the pgcrypto
-- extension — a privilege managed databases do not always grant.
create table request_log (
    id           uuid        primary key,
    subject      text,
    requested_at timestamptz not null default now(),
    result       text        not null
);

create index request_log_subject_time_idx on request_log (subject, requested_at desc);
