name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_server:
    name: Builds Server Side code

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose --manifest-path ./server/Cargo.toml
    - name: Run tests
      run: cargo test --verbose --manifest-path ./server/Cargo.toml
   
  build_client:
    name: Builds client side code and does cross-compiling
    
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose --manifest-path ./client/Cargo.toml
    - name: Run tests
      run: cargo test --verbose --manifest-path ./client/Cargo.toml
    - name: Install Cross 

      shell: bash
      run: |
        curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
        cargo binstall --no-confirm cross  
    - name: Build for raspberry pi
      run: cross build --verbose --manifest-path ./client/Cargo.toml --target armv7-unknown-linux-gnueabihf
    - name: Run tests for raspberry pi
      run: cross test --verbose --manifest-path ./client/Cargo.toml --target armv7-unknown-linux-gnueabihf
    - name: upload artifact
      uses: actions/upload-artifact@v4
      with:
         name: raspberry pi executable
         path: ./**/target/*/release/client